version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camlin_db
      MYSQL_USER: camlin
      MYSQL_PASSWORD: camlin_password 
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    networks:
      - mynetwork
  
  python:
    build: .
    container_name: python-container
    volumes:
      - ./app:/app       
    depends_on:
      - mysql
    networks:
      - mynetwork
    ports:
      - "8000:8000"         

volumes:
  mysql-data:

networks:
  mynetwork:
    driver: bridge